#!/usr/bin/env python

# from YouTube Engineer Man, https://www.youtube.com/watch?v=rbasThWVb-c

# curses documentation: https://docs.python.org/2/library/curses.html

import random
import curses

s = curses.initscr() # initialize and return whole screen
curses.curs_set(0) # turn off blinking cursor
sh, sw = s.getmaxyx() # return (y, x) of height and width of the window
w = curses.newwin(sh, sw, 0, 0) # return a new window
w.keypad(1) # escape sequences generated by some keys(keypad, function keys)...???
w.timeout(100) # escape sequences will not be timed out???

snk_x = sw/4
snk_y = sh/2

snake = [
    [snk_y, snk_x],
    [snk_y, snk_x-1],
    [snk_y, snk_x-2],
]

food = [sh/2, sw/2]
w.addch(food[0], food[1], 'X') # paint character at position

key = curses.KEY_RIGHT # Right-arrow

while True:
    next_key = w.getch() # get a character
    # key = key if next_key == -1 else next_key

    if next_key == -1 or \
        (key == curses.KEY_RIGHT and next_key == curses.KEY_LEFT) or \
        (key == curses.KEY_LEFT and next_key == curses.KEY_RIGHT) or \
        (key == curses.KEY_DOWN and next_key == curses.KEY_UP) or \
        (key == curses.KEY_UP and next_key == curses.KEY_DOWN):
        key = key
    else:
        key = next_key

    if snake[0][0] in [0, sh] or snake[0][1] in [0, sw] or snake[0] in snake[1:]:
        curses.endwin() # de-initialize curses library, return terminal to normal status
        quit()

    new_head = [snake[0][0], snake[0][1]]

    if key == curses.KEY_DOWN:
        new_head[0] += 1
    if key == curses.KEY_UP:
        new_head[0] -= 1
    if key == curses.KEY_LEFT:
        new_head[1] -= 1
    if key == curses.KEY_RIGHT:
        new_head[1] += 1

    snake.insert(0, new_head)

    if snake[0] == food:
        food = None
        while food is None:
            nf = [
                random.randint(1, sh-1),
                random.randint(1, sw-1),
            ]
            food = nf if nf not in snake else None
        w.addch(food[0], food[1], 'X')
    else:
        tail = snake.pop()
        w.addch(tail[0], tail[1], ' ')

    w.addch(snake[0][0], snake[0][1], 'Y')
